name: Terraform CD to LXD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: git-action-runner-vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install LXD Client
        run: |
          sudo apt update
          sudo apt install -y lxd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./lxc

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./lxc
